#!/usr/bin/python

import sys
import dbus

def extract_list(list):
	val = "["
	for i in list:
		val += " " + str(i)
	val += " ]"
	return val

bus = dbus.SystemBus()

record = dbus.Interface(bus.get_object("org.neard", sys.argv[1]),
						"org.neard.Record")

properties = record.GetProperties()

print "[ %s ]" % (sys.argv[1])

for key in properties.keys():
    val = str(properties[key])
    print "      %s = %s" % (key, val)
