#!/usr/bin/python

import dbus

bus = dbus.SessionBus()

manager = dbus.Interface(bus.get_object("org.near", "/"),
					"org.near.Manager")


properties = manager.GetProperties()

for path in properties["Adapters"]:
    print "[ %s ]" % (path)

    adapter = dbus.Interface(bus.get_object("org.near", path),
						"org.near.Adapter")

    properties = adapter.GetProperties()

    for key in properties.keys():
        if key in ["Powered"]:
            if properties[key] == dbus.Boolean(1):
                val = "true"
            else:
                val = "false"
        else:
            val = str(properties[key])
            
        print "        %s = %s" % (key, val)
