#!/usr/bin/python

import sys
import dbus

def help_text():
	print "Usage: %s <tag-path> <record-type> <...>" % (sys.argv[0])
	print "		If type is Text, parameters are <encoding> <language> <representation>"
	print "		If type is URI, parameters are <uri>"
	print "		If type is SmartPoster, parameters are <uri>"
	print "		If type is SMS, parameters are <phone number> <text>"
	print "		If type is E-Mail, parameters are <e-mail address>"
	print "e.g. < %s /org/neard/nfc0/tag0 Text UTF-8 en-US hello,NFC! >" % (sys.argv[0])
	print "e.g. < %s /org/neard/nfc0/tag0 URI http://www.nfc-forum.com >" % (sys.argv[0])
	print "e.g. < %s /org/neard/nfc0/tag0 SmartPoster http://www.nfc-forum.com >" % (sys.argv[0])
	print "e.g. < %s /org/neard/nfc0/tag0 SMS 0102030405 YourSMSMessage >" % (sys.argv[0])
	print "e.g. < %s /org/neard/nfc0/tag0 E-Mail test@test.com >" % (sys.argv[0])
	sys.exit(1)

if len(sys.argv) < 2:
	help_text()

bus = dbus.SystemBus()

tag = dbus.Interface(bus.get_object("org.neard", sys.argv[1]),
						"org.neard.Tag")

if sys.argv[2] in ["Text"]:
	tag.Write(({ "Type" : "Text",
			"Encoding" : sys.argv[3],
			"Language" : sys.argv[4],
			"Representation" : sys.argv[5] }))

elif sys.argv[2] in ["URI"]:
	tag.Write(({ "Type" : "URI",
			"URI" : sys.argv[3] }))

elif sys.argv[2] in ["SmartPoster"]:
	tag.Write(({ "Type" : "SmartPoster",
			"URI" : sys.argv[3] }))

elif sys.argv[2] in ["SMS"]:
        URI = "sms:"+sys.argv[3]+"?body="+sys.argv[4]
	tag.Write(({ "Type" : "URI",
			"URI" : URI }))

elif sys.argv[2] in ["E-Mail"]:
        URI = "mailto:"+sys.argv[3]
	tag.Write(({ "Type" : "URI",
			"URI" : URI }))

else:
	help_text()
