#!/bin/sh

if [ -f config.status ]; then
	make maintainer-clean
fi

./bootstrap && \
    ./configure --enable-maintainer-mode \
		--enable-debug \
		--enable-nfctype1=builtin \
		--enable-nfctype2=builtin \
		--enable-nfctype3=builtin \
		--enable-nfctype4=builtin \
		--prefix=/usr $*
