
plugin_cflags = -fvisibility=hidden -I$(srcdir)/gdbus \
					@DBUS_CFLAGS@ @GLIB_CFLAGS@
plugin_ldflags = -no-undefined -module -avoid-version

if NFCTYPE2
if NFCTYPE2_BUILTIN
builtin_modules += nfctype2
builtin_sources += plugins/nfctype2.c
else
plugin_LTLIBRARIES += plugins/nfctype2.la
plugin_objects += $(plugins_nfctype2_la_OBJECTS)
plugins_nfctype2_la_CFLAGS = $(plugin_cflags)
plugins_nfctype2_la_LDFLAGS = $(plugin_ldflags)
endif
endif